### ISSUE TITLE
Where is get-current-layout defined?

### ISSUE THREAD

**Issue by z3t0** [zarkone/stumpwm.d#1]
https://github.com/zarkone/stumpwm.d/blob/0f0f901aeb226a51928c5874d88afa2d6f525488/modeline.lisp#L41

Can you point me to where this function is defined, I can't seem to find it within your configuration and I don't think it is a part of stumpwm?

**Comment by zarkone** [comment]
sorry, i really need to make this repo usable out of the box (didn't think somebody actually tries to use it!)
Just commited this fn I used in collab with `kbdd` --  daemon which keeps the dictionary of `{ window: current_layout }` and switch layout when you switch between windows.

**Comment by z3t0** [comment]
Thank you so much for the quick response!

I was actually looking for tips on configuring the modeline and found your config from the reddit post: https://www.reddit.com/r/unixporn/comments/3qiyk1/stumpwm_gothamblue_modeline/

Thank you for uploading the config, it makes it a lot easier for the rest of us :smile:
